import { WeaponData } from '../types';

export const WEAPON_REGISTRY: Record<string, WeaponData> = {
  'AK-47': {
    id: 'AK-47',
    name: 'AK-47 Kalashnikov',
    category: 'rifle',
    damage: 44, // 7.62mm heavy punch
    fireRate: 600,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTime: 2.2,
    recoil: 4.6,
    accuracy: 88,
    range: 160,
    slot: 1,
    automatic: true,
    price: 2700,
    descriptionUz: 'Afsonaviy AK-47 Kalashnikov shturm miltig‘i. Yuqori o‘q zarbi va cheksiz ishonchlilik.',
    descriptionEn: 'Legendary AK-47 Kalashnikov assault rifle with high penetration and immense firepower.',
    descriptionRu: 'Легендарный автомат Калашникова АК-47 с мощным патроном 7.62мм и высокой пробивной силой.'
  },
  'AWM': {
    id: 'AWM',
    name: 'AWM Mergan Miltig‘i',
    category: 'sniper',
    damage: 500, // GUARANTEED ONE-SHOT KILL!
    oneShotKill: true,
    fireRate: 38, // Bolt-action precision
    magazineSize: 5,
    reserveAmmo: 25,
    reloadTime: 3.2,
    recoil: 8.5,
    accuracy: 100,
    range: 500,
    slot: 1,
    automatic: false,
    zoomFov: 16, // High magnification sniper scope
    price: 4750,
    descriptionUz: 'Afsonaviy AWM mergan miltig‘i (.338 Lapua). Har qanday nishonni bittada o‘ldiradi (1-Shot Kill)!',
    descriptionEn: 'Legendary AWM heavy precision sniper rifle. Guaranteed one-shot kill on any hit!',
    descriptionRu: 'Тяжелая снайперская винтовка AWM. Гарантированно уничтожает любую цель с одного выстрела!'
  },
  'AR-01': {
    id: 'AR-01',
    name: 'AR-01 Vektor',
    category: 'rifle',
    damage: 34,
    fireRate: 660, // 11 rps
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTime: 2.2,
    recoil: 3.8,
    accuracy: 88,
    range: 120,
    slot: 1,
    automatic: true,
    price: 2200,
    descriptionUz: 'Standart shturm miltig‘i. Har qanday jangovar sharoitda barqaror va ishonchli.',
    descriptionEn: 'Standard tactical assault rifle. Balanced recoil and high reliability in all combat situations.',
    descriptionRu: 'Стандартная штурмовая винтовка. Отличный баланс и надежность в любых условиях.'
  },
  'AR-02': {
    id: 'AR-02',
    name: 'AR-02 Bo‘ron',
    category: 'rifle',
    damage: 38,
    fireRate: 600,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTime: 2.4,
    recoil: 4.6,
    accuracy: 84,
    range: 140,
    slot: 1,
    automatic: true,
    descriptionUz: 'Yuqori kalibrli shturm quroli. Qattiq zarba va kuchli o‘t ochish qobiliyati.',
    descriptionEn: 'Heavy caliber assault rifle. High stopping power and penetration at mid ranges.',
    descriptionRu: 'Тяжелая штурмовая винтовка повышенного калибра с высоким останавливающим действием.'
  },
  'AR-03': {
    id: 'AR-03',
    name: 'AR-03 Lochin',
    category: 'rifle',
    damage: 31,
    fireRate: 750,
    magazineSize: 35,
    reserveAmmo: 140,
    reloadTime: 2.0,
    recoil: 3.2,
    accuracy: 91,
    range: 110,
    slot: 1,
    automatic: true,
    descriptionUz: 'Yengil taktik miltiq. Yuqori otish tezligi va boshqariluvchan orqaga tepish.',
    descriptionEn: 'Lightweight tactical rifle. High rate of fire with smooth recoil controllability.',
    descriptionRu: 'Облегченная тактическая винтовка с высокой скорострельностью и низкой отдачей.'
  },
  'SMG-01': {
    id: 'SMG-01',
    name: 'SMG-01 Qoplon',
    category: 'smg',
    damage: 25,
    fireRate: 850,
    magazineSize: 32,
    reserveAmmo: 160,
    reloadTime: 1.8,
    recoil: 2.6,
    accuracy: 80,
    range: 65,
    slot: 1,
    automatic: true,
    descriptionUz: 'Yaqin masofadagi janglar uchun o‘ta tezkor pulemyot-to‘pponcha.',
    descriptionEn: 'Ultra-fast submachine gun optimized for close quarters tactical room clearing.',
    descriptionRu: 'Скорострельный пистолет-пулемет, идеален для штурма закрытых помещений.'
  },
  'SMG-02': {
    id: 'SMG-02',
    name: 'SMG-02 Soya',
    category: 'smg',
    damage: 27,
    fireRate: 800,
    magazineSize: 40,
    reserveAmmo: 160,
    reloadTime: 2.1,
    recoil: 2.9,
    accuracy: 82,
    range: 75,
    slot: 1,
    automatic: true,
    descriptionUz: 'Katta sig‘imli magazin va o‘rnatilgan susturgichga ega SMG.',
    descriptionEn: 'Extended magazine submachine gun with integrated tactical suppression.',
    descriptionRu: 'Пистолет-пулемет с увеличенным магазином и интегрированным глушителем.'
  },
  'SG-01': {
    id: 'SG-01',
    name: 'SG-01 Qalqon',
    category: 'shotgun',
    damage: 18, // 18 x 8 pellets = 144 max close
    fireRate: 80,
    magazineSize: 8,
    reserveAmmo: 40,
    reloadTime: 2.8,
    recoil: 7.5,
    accuracy: 55,
    range: 35,
    slot: 1,
    automatic: false,
    pellets: 8,
    descriptionUz: 'Taktik sochma miltiq. Yaqin masofada dushmanga halokatli zarba beradi.',
    descriptionEn: 'Pump-action tactical shotgun delivering devastating point-blank destruction.',
    descriptionRu: 'Тактический дробовик с сокрушительным уроном на ближней дистанции.'
  },
  'SR-01': {
    id: 'SR-01',
    name: 'SR-01 Burgut',
    category: 'sniper',
    damage: 105, // one-shot to chest or head
    fireRate: 45,
    magazineSize: 5,
    reserveAmmo: 25,
    reloadTime: 3.2,
    recoil: 8.5,
    accuracy: 99,
    range: 300,
    slot: 1,
    automatic: false,
    zoomFov: 20,
    descriptionUz: 'Uzoq masofali og‘ir mergan miltig‘i. Katta optik nishonga ega.',
    descriptionEn: 'Heavy bolt-action precision sniper rifle with extreme long-range lethality.',
    descriptionRu: 'Тяжелая снайперская винтовка с мощной оптикой для уничтожения на больших дистанциях.'
  },
  'P-01': {
    id: 'P-01',
    name: 'P-01 Zarb',
    category: 'pistol',
    damage: 29,
    fireRate: 400,
    magazineSize: 15,
    reserveAmmo: 60,
    reloadTime: 1.5,
    recoil: 2.2,
    accuracy: 85,
    range: 50,
    slot: 2,
    automatic: false,
    descriptionUz: 'Yarim avtomatik ishonchli xizmat to‘pponchasi.',
    descriptionEn: 'Reliable semi-automatic sidearm pistol with crisp trigger response.',
    descriptionRu: 'Надежный полуавтоматический служебный пистолет с мягким спуском.'
  },
  'P-02': {
    id: 'P-02',
    name: 'P-02 Mergan',
    category: 'pistol',
    damage: 52,
    fireRate: 220,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadTime: 1.9,
    recoil: 6.0,
    accuracy: 92,
    range: 80,
    slot: 2,
    automatic: false,
    descriptionUz: 'Og‘ir kalibrli taktik to‘pponcha. Aniq va kuchli zarba beradi.',
    descriptionEn: 'High-caliber heavy tactical pistol with tremendous single-shot punch.',
    descriptionRu: 'Крупнокалиберный тактический пистолет с высокой убойной силой.'
  },
  'Tactical Knife': {
    id: 'Tactical Knife',
    name: 'Taktik Pichoq',
    category: 'knife',
    damage: 65,
    fireRate: 90,
    magazineSize: 1,
    reserveAmmo: 1,
    reloadTime: 0.1,
    recoil: 0.5,
    accuracy: 100,
    range: 2.2,
    slot: 3,
    automatic: false,
    descriptionUz: 'Maxsus bo‘linma jangovar pichog‘i. Jim va xavfli qurol.',
    descriptionEn: 'Military combat tactical blade forged from reinforced carbon steel.',
    descriptionRu: 'Боевой тактический нож специального назначения из углеродистой стали.'
  }
};

export const DEFAULT_PRIMARY_WEAPON = 'AK-47';
export const DEFAULT_SECONDARY_WEAPON = 'P-01';
export const DEFAULT_KNIFE = 'Tactical Knife';
