import { ZoneConfig } from '../types';

export const ZONES: ZoneConfig[] = [
  {
    id: 'desert_base',
    nameKey: 'desertBase',
    nameUz: 'Cho‘l Bazasi',
    nameEn: 'Desert Outpost',
    nameRu: 'База в Пустыне',
    descUz: 'Cho‘l hududidagi harbiy baza. Quruq iqlim, qum tepaliklari va mustahkamlangan angarlar.',
    descEn: 'Fortified military outpost situated across an arid desert plateau with hangars and watchtowers.',
    descRu: 'Укрепленная военная база посреди песчаных дюн с ангарами и смотровыми вышками.',
    difficulty: 'easy',
    environmentType: 'desert',
    defaultBotCount: 8,
    recommendedPlayers: '5 vs 5',
    objectiveUz: 'Harbiy bazani dushman hujumidan himoya qiling va sektorlarni ushlab turing.',
    objectiveEn: 'Defend the tactical base perimeter and secure strategic supply caches.',
    objectiveRu: 'Обороняйте периметр военной базы и удерживайте стратегические склады.',
    skyColor: 0xdfc999,
    groundColor: 0xd2b48c,
    fogColor: 0xdfc08f,
    fogDensity: 0.008,
    ambientColor: 0xffedd5,
    sunIntensity: 2.2,
    sunColor: 0xfff7ed,
    nightMode: false
  },
  {
    id: 'city_center',
    nameKey: 'cityCenter',
    nameUz: 'Shahar Markazi',
    nameEn: 'Downtown City',
    nameRu: 'Центр Города',
    descUz: 'Tashlandiq zamonaviy shahar. Ko‘p qavatli binolar, vayronalar, asfalt ko‘chalar va beton barrikadalar.',
    descEn: 'Deserted modern metropolis. Multi-story ruins, concrete barricades, asphalt streets, and tight urban alleys.',
    descRu: 'Заброшенный современный мегаполис. Разрушенные высотки, бетонные заграждения и узкие переулки.',
    difficulty: 'normal',
    environmentType: 'urban',
    defaultBotCount: 8,
    recommendedPlayers: '5 vs 5',
    objectiveUz: 'Shahar markazidagi nuqtani egallang va dushman snayperlarini yo‘q qiling.',
    objectiveEn: 'Capture the central plaza intersection and neutralize enemy sniper squads.',
    objectiveRu: 'Захватите перекресток центральной площади и ликвидируйте вражеские группы.',
    skyColor: 0x94a3b8,
    groundColor: 0x475569,
    fogColor: 0x94a3b8,
    fogDensity: 0.009,
    ambientColor: 0xe2e8f0,
    sunIntensity: 1.9,
    sunColor: 0xffffff,
    nightMode: false
  },
  {
    id: 'industrial_zone',
    nameKey: 'industrialZone',
    nameUz: 'Sanoat Hududi',
    nameEn: 'Industrial Complex',
    nameRu: 'Промзона',
    descUz: 'Katta zavod va omborlar joylashgan hudud. Neft rezervuarlari, metall quvurlar va sanoat kranlari.',
    descEn: 'Sprawling manufacturing refinery with oil storage tanks, steel pipes, gantry cranes, and warehouses.',
    descRu: 'Крупный заводской комплекс с нефтехранилищами, металлическими трубами и ангарами.',
    difficulty: 'normal',
    environmentType: 'industrial',
    defaultBotCount: 10,
    recommendedPlayers: '5 vs 5',
    objectiveUz: 'Sanoat hududidagi obyektni nazorat qiling va neft zaxiralarini himoya qiling.',
    objectiveEn: 'Secure the refinery control hub and prevent hostile sabotage of fuel storage.',
    objectiveRu: 'Установите контроль над промышленным узлом и защитите топливные терминалы.',
    skyColor: 0xa8a29e,
    groundColor: 0x57534e,
    fogColor: 0x78716c,
    fogDensity: 0.011,
    ambientColor: 0xf5f5f4,
    sunIntensity: 1.8,
    sunColor: 0xfef08a,
    nightMode: false
  },
  {
    id: 'mountain_fortress',
    nameKey: 'mountainFortress',
    nameUz: 'Tog‘ Qal’asi',
    nameEn: 'Mountain Fortress',
    nameRu: 'Горная Крепость',
    descUz: 'Tog‘lar orasidagi himoyalangan baza. Qoyalar, tosh bunkerlar, tor ko‘priklar va qor parchalari.',
    descEn: 'Heavily fortified alpine stronghold perched on steep rocky ridges with fortified concrete bunkers.',
    descRu: 'Высокогорная укрепленная крепость среди скал, каменных бункеров и узких мостов.',
    difficulty: 'hard',
    environmentType: 'mountain',
    defaultBotCount: 10,
    recommendedPlayers: '5 vs 5',
    objectiveUz: 'Tog‘ qal’asiga yetib boring va dushman qo‘mondonlik punktini qo‘lga oling.',
    objectiveEn: 'Infiltrate the summit fortress gatehouse and seize the enemy command bunker.',
    objectiveRu: 'Штурмуйте высокогорные укрепления и захватите командный бункер противника.',
    skyColor: 0xcfd8dc,
    groundColor: 0x78909c,
    fogColor: 0xb0bec5,
    fogDensity: 0.012,
    ambientColor: 0xe0f2fe,
    sunIntensity: 2.1,
    sunColor: 0xffffff,
    nightMode: false
  },
  {
    id: 'seaport',
    nameKey: 'seaport',
    nameUz: 'Port',
    nameEn: 'Cargo Seaport',
    nameRu: 'Морской Порт',
    descUz: 'Konteynerlar va katta yuk kemalari joylashgan port. Katta kranlar, suv havzasi va yuk omborlari.',
    descEn: 'Busy coastal shipping terminal with massive container stacks, cargo freighters, cranes, and wet docks.',
    descRu: 'Грузовой морской порт с огромными штабелями контейнеров, сухогрузами и портовыми кранами.',
    difficulty: 'hard',
    environmentType: 'port',
    defaultBotCount: 10,
    recommendedPlayers: '5 vs 5',
    objectiveUz: 'Port hududini nazorat qiling va kontrabanda yuklarini qo‘lga kiriting.',
    objectiveEn: 'Establish tactical dominance over container docks and secure cargo vessel deck.',
    objectiveRu: 'Обеспечьте контроль над доками с контейнерами и палубой грузового судна.',
    skyColor: 0x64748b,
    groundColor: 0x334155,
    fogColor: 0x64748b,
    fogDensity: 0.010,
    ambientColor: 0xbae6fd,
    sunIntensity: 1.7,
    sunColor: 0xf1f5f9,
    nightMode: false
  },
  {
    id: 'night_operation',
    nameKey: 'nightOperation',
    nameUz: 'Kecha Operatsiyasi',
    nameEn: 'Night Operation',
    nameRu: 'Ночная Операция',
    descUz: 'Tungi shahar va qorong‘i sanoat hududi. Projektorlar nuri, xira chiroqlar va qorong‘i soyalar.',
    descEn: 'Covert midnight strike in a blackout industrial district illuminated by tactical floodlights and embers.',
    descRu: 'Скрытная ночная операция в обесточенном промышленном секторе с тактическими прожекторами.',
    difficulty: 'extreme',
    environmentType: 'night',
    defaultBotCount: 12,
    recommendedPlayers: '6 vs 6',
    objectiveUz: 'Tungi operatsiyani yakunlang va dushmanning maxfiy serverini yo‘q qiling.',
    objectiveEn: 'Conduct midnight stealth assault and eliminate high-value hostile operatives.',
    objectiveRu: 'Выполните ночной рейд и уничтожьте ключевой командный узел врага.',
    skyColor: 0x050811,
    groundColor: 0x0f172a,
    fogColor: 0x070d18,
    fogDensity: 0.022,
    ambientColor: 0x1e293b,
    sunIntensity: 0.4,
    sunColor: 0x38bdf8,
    nightMode: true
  }
];
