import { Language } from './types';

export const translations = {
  uz: {
    // Game Title & Brand
    gameTitle: 'TACTICAL STRIKE: UZ',
    gameSubtitle: 'MAXSUS OPERATSIYA KUCHLARI',
    
    // Main Menu Buttons
    play: 'O‘YNASH',
    selectZone: 'ZONA TANLASH',
    settings: 'SOZLAMALAR',
    weapons: 'QUROLLAR',
    stats: 'STATISTIKA',
    exit: 'CHIQISH',
    quickMatch: 'TEZKOR O‘YIN',
    
    // Zone Selection
    zoneSelectTitle: 'OPERATSIYA ZONASINI TANLANG',
    difficulty: 'Murakkablik',
    environment: 'Hudud turi',
    botCount: 'Botlar soni',
    recommendedPlayers: 'Tavsiya etilgan tarkib',
    cancel: 'BEKOR QILISH',
    startMission: 'O‘YNASH',
    
    // Difficulties
    easy: 'OSON',
    normal: 'O‘RTA',
    hard: 'QIYIN',
    extreme: 'EKSTREMAL',
    
    // Game Modes
    gameMode: 'O‘yin rejimi',
    tdm: 'Jamoaviy Jang (TDM)',
    zone_control: 'Zona Nazorati',
    elimination: 'Tozalash Operatsiyasi',
    training: 'Mashg‘ulot Poligoni',
    survival: 'Omon Qolish',

    // Loading Screen
    loadingZone: 'ZONA YUKLANMOQDA...',
    systemCheck: 'Qurollar va aloqa tizimi tekshirilmoqda...',
    tips: [
      'O‘q-dorilaringizni nazorat qiling.',
      'Botlarning harakatiga e’tibor bering.',
      'Jamoangiz bilan birga harakat qiling.',
      'Bosh qismiga tekkanda (Headshot) zarba 2.5 barobar oshadi.',
      'O‘tirish (CTRL) nishonga olish aniqligini sezilarli oshiradi.',
      'O‘ng tugma bilan nishonga oling (ADS).'
    ],

    // HUD
    health: 'SALOMATLIK',
    armor: 'BRONYA',
    ammo: 'O‘Q-DORI',
    teamScore: 'JAMOALAR HISOBI',
    blueTeam: 'KO‘K JAMOA',
    redTeam: 'QIZIL JAMOA',
    objective: 'Vazifa',
    capturingZone: 'ZONA EGALLANMOQDA...',
    zoneCaptured: 'ZONA EGALLANDI!',
    hitConfirm: 'ZARB',
    headshot: 'BOSHDAN ZARB!',
    reloadPrompt: 'QAYTA O‘QLASH (R)',
    clickToLockPointer: 'O‘yinni boshqarish uchun ekranga bosing',
    reloading: 'O‘QLANMOQDA...',

    // Pause Menu
    pause: 'PAUZA',
    resume: 'DAVOM ETISH',
    pauseSettings: 'SOZLAMALAR',
    returnToZone: 'ZONAGA QAYTISH',
    mainMenu: 'ASOSIY MENYU',

    // Game Over & Results
    missionSuccess: 'MISSIYA MUVAFFAQIYATLI YAKUNLANDI',
    missionFailed: 'MISSIYA YAKUNLANDI',
    victory: 'G‘ALABA!',
    defeat: 'MAG‘LUBIYAT!',
    kills: 'Yo‘q qilinganlar',
    deaths: 'O‘limlar',
    score: 'Umumiy Ball',
    accuracy: 'Aniqlik darajasi',
    time: 'Jang vaqti',
    playAgain: 'QAYTA O‘YNASH',
    nextZone: 'KEYINGI ZONA',

    // Settings
    settingsTitle: 'TIZIM SOZLAMALARI',
    graphics: 'GRAFIKA SIFATI',
    low: 'Past',
    medium: 'O‘rta',
    high: 'Yuqori',
    ultra: 'Ultra',
    sound: 'OVOZ TIZIMI',
    masterVol: 'Umumiy Ovoz',
    musicVol: 'Musiqa Ovozi',
    effectsVol: 'Jang Effektlari',
    controls: 'BOSHQARUV',
    mouseSensitivity: 'Sichqoncha sezgirligi',
    invertMouseY: 'Sichqoncha Y o‘qini teskari qilish (Invert Y)',
    invertMouseYDesc: 'O‘chirilganda: tepaga surish - tepaga qarash, pastga surish - pastga qarash',
    language: 'TIL (LANGUAGE)',
    crosshair: 'PRITSEL SOZLAMASI',
    crosshairSize: 'Pritsel o‘lchami',
    crosshairThickness: 'Pritsel qalinligi',
    crosshairOpacity: 'Pritsel shaffofligi',
    save: 'SAQLASH',

    // Weapon Selection
    weaponArsenal: 'QUROL-YAROG‘ ARSENALI',
    damage: 'Zarar kuchi',
    fireRate: 'Otish tezligi',
    magCapacity: 'Magazin sig‘imi',
    range: 'Masofa',
    recoil: 'Orqaga tepish',
    selectWeapon: 'QUROLNI TANLASH',
    equipped: 'TANLANGAN',
    back: 'ORQAGA',

    // Stats Screen
    careerStats: 'JANGCHI STATISTIKASI',
    totalMatches: 'O‘tkazilgan janglar',
    totalKills: 'Jami yo‘q qilinganlar',
    totalDeaths: 'Jami o‘limlar',
    kdRatio: 'K/D Nisbati',
    winRate: 'G‘alaba foizi',
    bestScore: 'Eng yuqori ball',
    headshotsCount: 'Boshdan urilganlar',

    // Controls hints
    controlsHint: 'W/A/S/D - Harakat | BO‘SHLIQ (Space) - Sakrash | R yoki LKM - Otish | E - Qayta o‘qlash | B - Miltiq Do‘koni | 1, 2, 3 - Qurollar',
    buyMenuTitle: 'MILTIQ VA ARSENAL DO‘KONI',
    buyWeapon: 'SOTIB OLISH',
    purchased: 'SOTIB OLINDI',
    money: 'Mablag‘',
    insufficientFunds: 'Mablag‘ yetarli emas!',
    openShopBtn: 'DO‘KON (B)',
    buyArmor: 'Maxsus Bronya (100)',
    buyMedkit: 'Tibbiy To‘plam (100 HP)',
    buyAmmo: 'To‘liq O‘q-dori Zaxirasi',
    oneShotKillBadge: '1-SHOT KILL (BITTADA O‘LDIRADI)'
  },

  en: {
    gameTitle: 'TACTICAL STRIKE: UZ',
    gameSubtitle: 'SPECIAL OPERATIONS FORCES',
    play: 'PLAY',
    selectZone: 'SELECT ZONE',
    settings: 'SETTINGS',
    weapons: 'WEAPONS',
    stats: 'STATISTICS',
    exit: 'EXIT',
    quickMatch: 'QUICK MATCH',

    zoneSelectTitle: 'SELECT OPERATION ZONE',
    difficulty: 'Difficulty',
    environment: 'Environment',
    botCount: 'Number of Bots',
    recommendedPlayers: 'Recommended Roster',
    cancel: 'CANCEL',
    startMission: 'PLAY',

    easy: 'EASY',
    normal: 'NORMAL',
    hard: 'HARD',
    extreme: 'EXTREME',

    gameMode: 'Game Mode',
    tdm: 'Team Deathmatch',
    zone_control: 'Zone Control',
    elimination: 'Elimination',
    training: 'Training Ground',
    survival: 'Survival',

    loadingZone: 'LOADING ZONE...',
    systemCheck: 'Verifying weapons & tactical comms...',
    tips: [
      'Manage your ammunition reserves carefully.',
      'Observe bot movement patterns and flanking angles.',
      'Move and coordinate with your squad.',
      'Headshots deal 2.5x critical damage multiplier.',
      'Crouching (CTRL) significantly tightens your bullet spread.',
      'Aim Down Sights (Right Mouse) for precision at distance.'
    ],

    health: 'HEALTH',
    armor: 'ARMOR',
    ammo: 'AMMO',
    teamScore: 'TEAM SCORE',
    blueTeam: 'BLUE TEAM',
    redTeam: 'RED TEAM',
    objective: 'Objective',
    capturingZone: 'CAPTURING ZONE...',
    zoneCaptured: 'ZONE CAPTURED!',
    hitConfirm: 'HIT',
    headshot: 'HEADSHOT!',
    reloadPrompt: 'RELOAD (R)',
    clickToLockPointer: 'Click anywhere to capture mouse and control aim',
    reloading: 'RELOADING...',

    pause: 'PAUSE',
    resume: 'RESUME',
    pauseSettings: 'SETTINGS',
    returnToZone: 'SELECT ZONE',
    mainMenu: 'MAIN MENU',

    missionSuccess: 'MISSION ACCOMPLISHED',
    missionFailed: 'MISSION FAILED',
    victory: 'VICTORY!',
    defeat: 'DEFEAT!',
    kills: 'Enemies Eliminated',
    deaths: 'Casualties',
    score: 'Combat Score',
    accuracy: 'Accuracy',
    time: 'Operation Time',
    playAgain: 'PLAY AGAIN',
    nextZone: 'NEXT ZONE',

    settingsTitle: 'SYSTEM SETTINGS',
    graphics: 'GRAPHICS QUALITY',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    ultra: 'Ultra',
    sound: 'AUDIO SYSTEM',
    masterVol: 'Master Volume',
    musicVol: 'Music Volume',
    effectsVol: 'Combat SFX',
    controls: 'CONTROLS',
    mouseSensitivity: 'Mouse Sensitivity',
    invertMouseY: 'Invert Mouse Y-Axis',
    invertMouseYDesc: 'Standard: push up to look up, pull down to look down',
    language: 'LANGUAGE',
    crosshair: 'CROSSHAIR CONFIG',
    crosshairSize: 'Crosshair Size',
    crosshairThickness: 'Thickness',
    crosshairOpacity: 'Opacity',
    save: 'SAVE',

    weaponArsenal: 'WEAPONS ARSENAL',
    damage: 'Damage',
    fireRate: 'Fire Rate',
    magCapacity: 'Magazine Capacity',
    range: 'Effective Range',
    recoil: 'Recoil Control',
    selectWeapon: 'EQUIP WEAPON',
    equipped: 'EQUIPPED',
    back: 'BACK',

    careerStats: 'CAREER COMBAT STATS',
    totalMatches: 'Matches Deployed',
    totalKills: 'Total Eliminations',
    totalDeaths: 'Total Casualties',
    kdRatio: 'K/D Ratio',
    winRate: 'Win Rate',
    bestScore: 'High Score',
    headshotsCount: 'Headshots',

    controlsHint: 'W/A/S/D - Move | SPACE - Jump | R or LMB - Fire | E - Reload | B - Buy Arsenal | 1, 2, 3 - Weapons',
    buyMenuTitle: 'TACTICAL BUY ARSENAL',
    buyWeapon: 'PURCHASE',
    purchased: 'EQUIPPED',
    money: 'Cash',
    insufficientFunds: 'Insufficient Funds!',
    openShopBtn: 'SHOP (B)',
    buyArmor: 'Heavy Armor (100)',
    buyMedkit: 'Field Medkit (100 HP)',
    buyAmmo: 'Ammunition Crate',
    oneShotKillBadge: '1-SHOT KILL (INSTANT ELIMINATION)'
  },

  ru: {
    gameTitle: 'TACTICAL STRIKE: UZ',
    gameSubtitle: 'СИЛЫ СПЕЦИАЛЬНЫХ ОПЕРАЦИЙ',
    play: 'ИГРАТЬ',
    selectZone: 'ВЫБОР ЗОНЫ',
    settings: 'НАСТРОЙКИ',
    weapons: 'ОРУЖИЕ',
    stats: 'СТАТИСТИКА',
    exit: 'ВЫХОД',
    quickMatch: 'БЫСТРЫЙ БОЙ',

    zoneSelectTitle: 'ВЫБЕРИТЕ ЗОНУ ОПЕРАЦИИ',
    difficulty: 'Сложность',
    environment: 'Тип местности',
    botCount: 'Количество ботов',
    recommendedPlayers: 'Рекомендуемый состав',
    cancel: 'ОТМЕНА',
    startMission: 'ИГРАТЬ',

    easy: 'ЛЕГКО',
    normal: 'НОРМАЛЬНО',
    hard: 'СЛОЖНО',
    extreme: 'ЭКСТРЕМАЛЬНО',

    gameMode: 'Режим игры',
    tdm: 'Командный бой (TDM)',
    zone_control: 'Захват точек',
    elimination: 'Ликвидация',
    training: 'Тренировочный полигон',
    survival: 'Выживание',

    loadingZone: 'ЗОНА ЗАГРУЖАЕТСЯ...',
    systemCheck: 'Проверка систем вооружения и тактической связи...',
    tips: [
      'Контролируйте расход боеприпасов.',
      'Следите за тактическими перемещениями ботов.',
      'Действуйте слаженно со своей командой.',
      'Выстрел в голову наносит в 2.5 раза больше урона.',
      'Приседание (CTRL) существенно снижает отдачу и разброс.',
      'Используйте прицеливание (ПКМ) для точной стрельбы на дистанции.'
    ],

    health: 'ЗДОРОВЬЕ',
    armor: 'БРОНЯ',
    ammo: 'БОЕПРИПАСЫ',
    teamScore: 'СЧЕТ КОМАНД',
    blueTeam: 'СИНЯЯ КОМАНДА',
    redTeam: 'КРАСНАЯ КОМАНДА',
    objective: 'Задача',
    capturingZone: 'ЗАХВАТ ЗОНЫ...',
    zoneCaptured: 'ЗОНА ЗАХВАЧЕНА!',
    hitConfirm: 'УДАР',
    headshot: 'В ГОЛОВУ!',
    reloadPrompt: 'ПЕРЕЗАРЯДКА (R)',
    clickToLockPointer: 'Нажмите в любое место экрана для захвата мыши',
    reloading: 'ПЕРЕЗАРЯДКА...',

    pause: 'ПАУЗА',
    resume: 'ПРОДОЛЖИТЬ',
    pauseSettings: 'НАСТРОЙКИ',
    returnToZone: 'К ВЫБОРУ ЗОНЫ',
    mainMenu: 'ГЛАВНОЕ МЕНЮ',

    missionSuccess: 'МИССИЯ УСПЕШНО ЗАВЕРШЕНА',
    missionFailed: 'МИССИЯ ПРОВАЛЕНА',
    victory: 'ПОБЕДА!',
    defeat: 'ПОРАЖЕНИЕ!',
    kills: 'Уничтожено врагов',
    deaths: 'Смертей',
    score: 'Боевой счет',
    accuracy: 'Точность стрельбы',
    time: 'Время операции',
    playAgain: 'ИГРАТЬ СНОВА',
    nextZone: 'СЛЕДУЮЩАЯ ЗОНА',

    settingsTitle: 'СИСТЕМНЫЕ НАСТРОЙКИ',
    graphics: 'КАЧЕСТВО ГРАФИКИ',
    low: 'Низкое',
    medium: 'Среднее',
    high: 'Высокое',
    ultra: 'Ультра',
    sound: 'ЗВУКОВАЯ СИСТЕМА',
    masterVol: 'Общая громкость',
    musicVol: 'Громкость музыки',
    effectsVol: 'Эффекты боя',
    controls: 'УПРАВЛЕНИЕ',
    mouseSensitivity: 'Чувствительность мыши',
    invertMouseY: 'Инверсия оси Y мыши',
    invertMouseYDesc: 'По умолчанию: вверх — взгляд вверх, вниз — взгляд вниз',
    language: 'ЯЗЫК (LANGUAGE)',
    crosshair: 'НАСТРОЙКА ПРИЦЕЛА',
    crosshairSize: 'Размер прицела',
    crosshairThickness: 'Толщина линий',
    crosshairOpacity: 'Прозрачность',
    save: 'СОХРАНИТЬ',

    weaponArsenal: 'ОРУЖЕЙНЫЙ АРСЕНАЛ',
    damage: 'Урон',
    fireRate: 'Скорострельность',
    magCapacity: 'Емкость магазина',
    range: 'Дальность',
    recoil: 'Контроль отдачи',
    selectWeapon: 'ВЫБРАТЬ ОРУЖИЕ',
    equipped: 'ВЫБРАНО',
    back: 'НАЗАД',

    careerStats: 'СТАТИСТИКА БОЙЦА',
    totalMatches: 'Сыграно матчей',
    totalKills: 'Всего уничтожено',
    totalDeaths: 'Потерь',
    kdRatio: 'Соотношение K/D',
    winRate: 'Процент побед',
    bestScore: 'Лучший результат',
    headshotsCount: 'Выстрелов в голову',

    controlsHint: 'W/A/S/D - Движение | ПРОБЕЛ - Прыжок | R или ЛКМ - Огонь | E - Перезарядка | B - Магазин оружия | 1, 2, 3 - Оружие',
    buyMenuTitle: 'ОРУЖЕЙНЫЙ МАГАЗИН',
    buyWeapon: 'КУПИТЬ',
    purchased: 'КУПЛЕНО',
    money: 'Баланс',
    insufficientFunds: 'Недостаточно средств!',
    openShopBtn: 'МАГАЗИН (B)',
    buyArmor: 'Тяжелая броня (100)',
    buyMedkit: 'Аптечка первой помощи (100 HP)',
    buyAmmo: 'Боекомплект патронов',
    oneShotKillBadge: '1-SHOT KILL (УБИВАЕТ С 1 ВЫСТРЕЛА)'
  }
};
